apiVersion: apps/v1
kind: Deployment
metadata:
  name: chasing-cats
  namespace: atlas-production
  labels:
    app: chasing-cats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chasing-cats
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chasing-cats
    spec:
      containers:
        - name: chasing-cats
          image: PLACEHOLDER_ECR_REGISTRY/chasing-cats:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: POSTMAN_INSIGHTS_WORKSPACE_ID
              value: "a50959cb-b5b5-4e89-823d-a57e88f658f4"
            - name: POSTMAN_INSIGHTS_SYSTEM_ENV
              value: "936898ce-cf73-4feb-827e-8a0e9d5e695e"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
      terminationGracePeriodSeconds: 30
