apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chasing-cats
  namespace: atlas-production
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
  labels:
    app: chasing-cats
spec:
  rules:
    - host: chasing-cats.atlas.shivemind.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chasing-cats
                port:
                  number: 80
