apiVersion: v1
kind: Service
metadata:
  name: chasing-cats
  namespace: atlas-production
  labels:
    app: chasing-cats
spec:
  type: ClusterIP
  selector:
    app: chasing-cats
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
