name: Postman Catalog Link
on:
  workflow_dispatch:

jobs:
  link-workspace:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: postman-cs/postman-repo-sync-action@v0
        with:
          project-name: chasing-cats
          workspace-id: a50959cb-b5b5-4e89-823d-a57e88f658f4
          generate-ci-workflow: false
          repo-write-mode: none
          environments-json: '["prod","dev"]'
          env-runtime-urls-json: '{"prod":"https://chasing-cats.vercel.app","dev":"http://localhost:3000"}'
          postman-api-key: ${{ secrets.POSTMAN_API_KEY }}
          postman-access-token: ${{ secrets.POSTMAN_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}